openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing user recipes — creating, viewing, updating, and deleting.

tags:
  - name: Tasteorama
    description: Operations with recipes.
  - name: Auth
    description: Auth operations.
  - name: Categories
    description: Categories operations

servers:
  - url: http://127.0.0.1:3000
    description: Локальний сервер для розробки
  - url: https://nodejs-hw-mongodb-iy1l.onrender.com
    description: Продакшн-сервер на Render

paths:
  /api/recepies/{id}:
    get:
      $ref: ../swagger/paths/recepies/getById.yaml
  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /api/recipes/addFavorite/{recipeId}:
    post:
      $ref: ../swagger/paths/recipes/addFavorite.yaml

  /api/recipes/favoriteRecipes:
    get:
      $ref: ../swagger/paths/recipes/favoriteRecipes.yaml
      
  /api/recipes/own/{recipeId}:
    delete:
      $ref: ../swagger/paths/recipes/deleteOwnRecipe.yaml

  /api/categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
