openapi: 3.1.0

info:
  version: 1.0.0
  title: Tasteorama APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing user recipes: creating, viewing, updating, and deleting.

tags:
  - name: Tasteorama
    description: Operations with recipes.
  - name: Auth
    description: Auth operations.

servers:
  - url: http://127.0.0.1:3000
    description: Локальний сервер для розробки
  - url: https://nodejs-hw-mongodb-iy1l.onrender.com
    description: Продакшн-сервер на Render

paths:
  /api/auth/register:
    post:
      $ref: './paths/auth/register.yaml'

  /api/auth/login:
    post:
      $ref: './paths/auth/login.yaml'

  /api/recipes/addFavorite/{recipeId}:
    post:
      $ref: './paths/recipes/addFavorite.yaml'

  /api/recipes/favoriteRecipes:
    get:
      $ref: './paths/recipes/favoriteRecipes.yaml'
  /api/recipes/own/{recipeId}:
    delete:
      $ref: './paths/recipes/deleteOwnRecipe.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


